/**
 * StringTokenizer takes a String and splits it into tokens based on one or more delimeters. It has
 * three constructors:
 *      StringTokenizer(String src)
 *      StringTokenizer(String src, String delim)
 *      StringTokenizer(String src, String delim, boolean returnDelims)
 *
 * All three constructors take a source string to split. The first constructor uses the default set of
 * whitespace delimeters (space, tab, form feed, newline and carriage return).
 *
 * The second constructor also takes a String which specifies one or more delimeters e.g. "=" or ",:;".
 *
 * The third constructor also takes a boolean as to whether include the delimeters in the splitting
 * result.
 *
 * The number of tokens generated by the tokenizer can be found with countTokens().
 */

import java.util.StringTokenizer;
import java.util.List;
import java.util.ArrayList;
import java.util.Collections;
import java.util.stream.Collectors;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileNotFoundException;
import java.io.IOException;

public class App {

    //==============================================================================================
    // Splits a String using the default set of delimeters. Here it splits at the space char.
    // result: [It, does, not, matter, how, slowly, you, go, ....]
    //==============================================================================================
    static void stringTokenizer1() {
        String quote = "It does not matter how slowly you go so long as you do not stop";
        StringTokenizer tokenizer = new StringTokenizer(quote);

        List<String> tokens = new ArrayList<>();
        while (tokenizer.hasMoreTokens()) {
            tokens.add(tokenizer.nextToken());
        }
    }

    //==============================================================================================
    // Splits a string using a custom delimeter.
    // result: [key1=value1, key2=value2, key3=value3]
    //==============================================================================================
    static void stringTokenizer2() {
        String input = "key1=value1;key2=value2;key3=value3";
        String delim = ";";
        StringTokenizer tokenizer = new StringTokenizer(input, delim);

        List<String> tokens = new ArrayList<>();
        while (tokenizer.hasMoreTokens()) {
            tokens.add(tokenizer.nextToken());
        }
    }

    //==============================================================================================
    // Splits a string using a custom delimeter and includes the delims in the results.
    // result: [ key1, =, value1, ;, key2, =, value2, ;, ... ]
    //==============================================================================================
    static void stringTokenizer3() {
        String input = "key1=value1;key2=value2;key3=value3";
        String delims = "=;";
        boolean includeDelims = true;
        StringTokenizer tokenizer = new StringTokenizer(input, delims, includeDelims);

        List<String> tokens = new ArrayList<>();
        while (tokenizer.hasMoreTokens()) {
            tokens.add(tokenizer.nextToken());
        }
    }

    //==============================================================================================
    // StringTokenizer works nicely with streams too ...
    //==============================================================================================
    static void stringTokenizer4() {
        String input = "Wheresoever you go, go with all your heart";

        List<String> tokens = Collections.list(new StringTokenizer(input)).stream()
            .map(token -> (String) token) // must cast to String here
            .collect(Collectors.toList());
    }

    //==============================================================================================
    // Find how many tokens were generated ...
    //==============================================================================================
    static void stringTokenizer5() {
        String input = "Wheresoever you go, go with all your heart";
        StringTokenizer tokenizer = new StringTokenizer(input);

        int numTokens = tokenizer.countTokens();
    }

    //==============================================================================================
    // Read data from csv file and tokenize it
    //==============================================================================================
    static void stringTokenizer6() {
        try (BufferedReader reader = new BufferedReader(new FileReader("data.csv"))) {

            List<String> tokens = new ArrayList<>();
            String line = "";
            String delim = ",";

            while ((line = reader.readLine()) != null) {
                StringTokenizer tokenizer = new StringTokenizer(line, delim);
                while (tokenizer.hasMoreTokens())
                    tokens.add(tokenizer.nextToken());
            }
        }
        catch (FileNotFoundException ex) { ex.printStackTrace(); }
        catch (IOException ex) { ex.printStackTrace(); }
    }

    public static void main(String[] args) {
        stringTokenizer1();
        stringTokenizer2();
        stringTokenizer3();
        stringTokenizer4();
        stringTokenizer5();
        stringTokenizer6();
    }
}
